import { ActionState } from '../assets/scripts/core/ActionState';
import { createWeaponRuntime, MAP_IDS, MAP_SCENE_GROUPS, MISSION_IDS, opticForWeapon, unlockedPrimaryWeapons, WEAPONS } from '../assets/scripts/core/GameTypes';
import { defaultProfile, ProfileStore, repairProfile } from '../assets/scripts/core/ProfileStore';
import { aiCombatSkill, applyExperience, applyVerticalLook, consumeShot, damageAtDistance, experienceForLevel, finishReload, handlingMobility, IdempotencySet, levelFromExperience, purchaseAttachment, radialDamage, rewardCoins, rewardExperience, safeDelta, stepCriticalSpring } from '../assets/scripts/core/Rules';

let passed = 0;
function check(condition: unknown, message: string): void {
  if (!condition) throw new Error(message);
  passed += 1;
}

const m16 = WEAPONS.m16;
const gun = createWeaponRuntime('m16');
check(consumeShot(gun, m16, 0), 'first shot must fire');
check(gun.magazine === 29 && gun.reserve === 600, 'successful shot deducts exactly one round');
check(!consumeShot(gun, m16, 0.001), 'fire rate must reject rapid shot');
check(!consumeShot(createWeaponRuntime('m16'), m16, -Infinity), 'invalid negative-infinity timing is rejected');
const m16Cadence = createWeaponRuntime('m16');
check(consumeShot(m16Cadence, m16, 0) && !consumeShot(m16Cadence, m16, 0.074) && consumeShot(m16Cadence, m16, 0.075), 'M16 800 RPM cadence');
const akmCadence = createWeaponRuntime('akm');
check(consumeShot(akmCadence, WEAPONS.akm, 0) && !consumeShot(akmCadence, WEAPONS.akm, 0.099) && consumeShot(akmCadence, WEAPONS.akm, 0.1), 'AKM 600 RPM cadence');
gun.magazine = 0;
check(!consumeShot(gun, m16, 10), 'empty magazine must not fire');
gun.magazine = 27;
gun.reserve = 2;
check(finishReload(gun, m16) === 2 && gun.magazine === 29 && gun.reserve === 0, 'partial reload must consume actual reserve');
check(gun.magazine >= 0 && gun.reserve >= 0, 'ammo must stay non-negative');
check(m16.automatic && m16.roundsPerMinute === 800, 'M16 must be 800 RPM automatic');
check(WEAPONS.akm.roundsPerMinute === 600, 'AKM fire rate');
check(WEAPONS.mp5.roundsPerMinute === 800 && WEAPONS.m249.roundsPerMinute === 750, 'blue weapon fire rates');
check(WEAPONS.aks74u.roundsPerMinute === 800 && WEAPONS.pkm.roundsPerMinute === 700, 'red weapon fire rates');
check(WEAPONS.rpk.roundsPerMinute === 600 && WEAPONS.rpk.magazineSize === 75 && WEAPONS.rpk.reserveAmmo === 750, 'RPK flexible red-team loadout');
check(WEAPONS.glock17.magazineSize === 17 && !WEAPONS.glock17.automatic, 'Glock 17 semi-auto capacity');
check(WEAPONS.m4a1.team==='blue'&&WEAPONS.ak74.team==='red'&&WEAPONS.m4a1.magazineSize===30&&WEAPONS.ak74.magazineSize===30,'level-three rifles use correct teams and magazines');
check(WEAPONS.m16.magazineSize === 30 && WEAPONS.m16.reserveAmmo === 600 && WEAPONS.akm.reserveAmmo === 600, 'rifle ammunition capacity');
check(WEAPONS.mp5.magazineSize === 30 && WEAPONS.mp5.reserveAmmo === 600 && WEAPONS.aks74u.reserveAmmo === 600, 'SMG ammunition capacity');
check(WEAPONS.m249.magazineSize === 150 && WEAPONS.m249.reserveAmmo === 1200 && WEAPONS.pkm.magazineSize === 150 && WEAPONS.pkm.reserveAmmo === 1200, 'LMG ammunition capacity');
check(WEAPONS.m2hb.magazineSize===200&&WEAPONS.m2hb.reserveAmmo===1200&&WEAPONS.kord.magazineSize===200&&WEAPONS.kord.reserveAmmo===1200,'heavy machine gun ammunition capacity');
check(WEAPONS.m107.magazineSize===10&&WEAPONS.m107.reserveAmmo===50&&WEAPONS.svd.magazineSize===10&&WEAPONS.svd.reserveAmmo===50&&WEAPONS.m200.magazineSize===7&&WEAPONS.m200.reserveAmmo===35,'sniper ammunition capacity');
check(!WEAPONS.m107.automatic&&!WEAPONS.m200.automatic&&!WEAPONS.svd.automatic,'all sniper rifles are semi-automatic');
check(WEAPONS.awm.magazineSize===10&&WEAPONS.awm.reserveAmmo===50&&!WEAPONS.awm.automatic&&opticForWeapon('awm','none')==='4x','AWM is a four-power air-drop-only sniper');
check(opticForWeapon('svd','none')==='4x'&&opticForWeapon('m107','none')==='6x'&&opticForWeapon('m200','red-dot')==='6x','sniper rifles use fixed built-in optics');
check(WEAPONS.m107.damageNear>WEAPONS.m2hb.damageNear&&WEAPONS.m2hb.damageNear>WEAPONS.kord.damageNear&&WEAPONS.kord.damageNear>WEAPONS.m200.damageNear,'new weapon damage ranking');
check(WEAPONS.m200.falloffEnd>WEAPONS.m107.falloffEnd&&WEAPONS.m2hb.falloffEnd>WEAPONS.kord.falloffEnd,'M200 range leads and M2HB outranges KORD');
check(WEAPONS.m2hb.roundsPerMinute===650&&WEAPONS.kord.roundsPerMinute===700,'heavy machine gun fire rates');
check(MAP_IDS.length===16&&MAP_SCENE_GROUPS.length===8&&MAP_SCENE_GROUPS.every(group=>group.maps.length===2)&&new Set(MAP_SCENE_GROUPS.flatMap(group=>group.maps)).size===16,'eight scene families provide sixteen unique maps');
check(MISSION_IDS.length===21&&new Set(MISSION_IDS).size===21&&MISSION_IDS.includes('hostage-rescue')&&MISSION_IDS.includes('bomb-defusal')&&MISSION_IDS.includes('vip-escort')&&MISSION_IDS.includes('cache-defense')&&MISSION_IDS.includes('evacuation-cover')&&MISSION_IDS.includes('battle-royale')&&MISSION_IDS.includes('safehouse-raid')&&MISSION_IDS.includes('supply-line-disruption'),'twenty-one distinct tactical missions are registered');
check(createWeaponRuntime('glock17').magazine === 17 && createWeaponRuntime('glock17').reserve === 119, 'Glock ammunition remains independent');
check(WEAPONS.akm.verticalRecoil > WEAPONS.m16.verticalRecoil && WEAPONS.pkm.verticalRecoil > WEAPONS.aks74u.verticalRecoil, 'weapon recoil tiers');
check(damageAtDistance(m16, 0, false) === 32, 'near damage');
check(damageAtDistance(m16, 200, false) === 21, 'far damage');
const categoryReloadMax=(category:string)=>Math.max(...Object.values(WEAPONS).filter(weapon=>weapon.category===category).map(weapon=>weapon.reloadSeconds));
const categoryReloadMin=(category:string)=>Math.min(...Object.values(WEAPONS).filter(weapon=>weapon.category===category).map(weapon=>weapon.reloadSeconds));
check(categoryReloadMax('pistol')<categoryReloadMin('smg')&&categoryReloadMax('smg')<categoryReloadMin('rifle')&&categoryReloadMax('rifle')<categoryReloadMin('lmg')&&categoryReloadMax('lmg')<categoryReloadMin('sniper')&&categoryReloadMax('sniper')<categoryReloadMin('hmg'),'reload speeds follow pistol-smg-rifle-lmg-sniper-hmg order');
check(Object.values(WEAPONS).every(weapon=>weapon.weightKg>0)&&WEAPONS.m2hb.weightKg>WEAPONS.kord.weightKg&&WEAPONS.kord.weightKg>WEAPONS.m107.weightKg,'weapon weights support handling mobility');
check(handlingMobility(WEAPONS.glock17.weightKg)>handlingMobility(WEAPONS.m4a1.weightKg)&&handlingMobility(WEAPONS.m4a1.weightKg)>handlingMobility(WEAPONS.m249.weightKg)&&handlingMobility(WEAPONS.m249.weightKg)>handlingMobility(WEAPONS.m2hb.weightKg),'heavier weapons reduce carrying movement monotonically');
const friendlySkills=Array.from({length:12},(_,index)=>aiCombatSkill(index,false,0));
const enemySkills=Array.from({length:12},(_,index)=>aiCombatSkill(index,true,7));
const average=(values:number[])=>values.reduce((sum,value)=>sum+value,0)/values.length;
check(average(enemySkills)>average(friendlySkills)+0.065,'enemy AI remains stronger than friendly AI after the fine balance adjustment');
check(Math.max(...enemySkills)<=0.979&&Math.min(...friendlySkills)>=0.82,'AI skill stays challenging but below near-perfect accuracy');
const playerWeapon=createWeaponRuntime('m16'),aiWeapon=createWeaponRuntime('m16');
for(const time of [0,0.075,0.15,0.225])check(consumeShot(playerWeapon,m16,time)===consumeShot(aiWeapon,m16,time),'player and AI share weapon cadence');
check(playerWeapon.magazine===aiWeapon.magazine&&playerWeapon.reserve===aiWeapon.reserve&&damageAtDistance(m16,60,false)===damageAtDistance(WEAPONS.m16,60,false),'same weapon has identical combat performance for player and AI');
check(radialDamage(100, 7, 0, false) === 100, 'grenade center damage');
check(radialDamage(100, 7, 8, false) === 0, 'grenade outside radius');
check(radialDamage(100, 7, 3.5, true) === 10, 'occluded grenade damage');
check(safeDelta(2) === 0.05 && safeDelta(-1) === 0, 'frame delta clamp');
check(applyVerticalLook(0, 10, 0.1, false) === 1 && applyVerticalLook(0, -10, 0.1, false) === -1, 'default vertical look direction');
check(applyVerticalLook(0, 10, 0.1, true) === -1 && applyVerticalLook(0, -10, 0.1, true) === 1, 'inverted vertical look direction');
check(applyVerticalLook(79, 100, 0.5, false) === 80 && applyVerticalLook(-79, -100, 0.5, false) === -80, 'vertical look clamp');
const springSingle = stepCriticalSpring(0, 8, 12, 0.04);
let springStepped = { position: 0, velocity: 8 };
for (let i = 0; i < 4; i += 1) springStepped = stepCriticalSpring(springStepped.position, springStepped.velocity, 12, 0.01);
check(Math.abs(springSingle.position - springStepped.position) < 1e-9 && Math.abs(springSingle.velocity - springStepped.velocity) < 1e-9, 'recoil spring is frame-rate independent');

const profile = defaultProfile();
check(profile.loadouts.awm.optic==='4x','default and repaired profiles include the built-in AWM optic');
check(purchaseAttachment(profile, 'red-dot') === 'purchased' && profile.coins === 400, 'attachment purchase');
check(purchaseAttachment(profile, 'red-dot') === 'owned' && profile.coins === 400, 'duplicate purchase idempotency');
profile.coins = 2000;
check(purchaseAttachment(profile, '2x') === 'purchased' && profile.coins === 1100, 'second purchase');
profile.coins = 799;
check(purchaseAttachment(profile, 'grip') === 'insufficient' && profile.coins === 799, 'insufficient purchase');
check(rewardCoins({ kills: 3, completed: true, won: true }) === 360, 'match reward');
check(rewardExperience({ kills: 3, completed: true, won: true }) === 550, 'experience reward');
check(experienceForLevel(2) === 350 && experienceForLevel(3) === 950 && levelFromExperience(949) === 2, 'level requirements increase');
const progression = defaultProfile(); const levelResult = applyExperience(progression, 350);
check(progression.level === 2 && progression.xp === 350 && levelResult.levels === 1 && levelResult.coinReward === 250, 'level-up applies shared XP and coin reward');
check(unlockedPrimaryWeapons('blue',1).join(',') === 'm16' && unlockedPrimaryWeapons('blue',3).includes('m4a1')&&unlockedPrimaryWeapons('red',3).includes('ak74')&&!unlockedPrimaryWeapons('red',3).includes('rpk'), 'level-three rifles shift existing unlock progression');
const repaired = repairProfile({ version: 1, coins: -50, level: 2, ownedAttachments: ['grip', 'barrel', 'invalid', 'grip'], settings: { sfxVolume: 9 }, loadouts: { m16: { optic: '2x', grip: true, barrel: true } } });
check(repaired.coins === 0 && repaired.ownedAttachments.length === 2, 'corrupt profile recovery');
check(repaired.loadouts.m16.optic === 'none' && repaired.loadouts.m16.grip && repaired.loadouts.m16.barrel === 'barrel', 'loadout compatibility repair');
check(repaired.version === 3 && repaired.level === 2 && repaired.xp === 350, 'version-one profile migrates progression safely');
check(repaired.selectedPrimary.blue==='m16'&&repaired.selectedPrimary.red==='akm'&&repaired.loadouts.m4a1.optic==='none'&&repaired.loadouts.ak74.optic==='none','saved primary weapons and new rifle loadouts migrate safely');
const selectedProfile=repairProfile({version:3,xp:950,coins:1000,selectedPrimary:{blue:'m4a1',red:'ak74'},loadouts:{}});
check(selectedProfile.selectedPrimary.blue==='m4a1'&&selectedProfile.selectedPrimary.red==='ak74','armory primary selections persist for both teams');
check(repaired.loadouts.mp5.optic==='none'&&repaired.loadouts.rpk.optic==='none'&&repaired.loadouts.m107.optic==='6x'&&repaired.loadouts.m200.optic==='6x'&&repaired.loadouts.svd.optic==='4x'&&repaired.loadouts.glock17.optic==='none','new weapon loadout defaults and built-in sniper optics');
check(repaired.settings.sfxVolume === 1, 'settings clamped');
check(defaultProfile().settings.invertVerticalLook === false && repairProfile({ settings: {} }).settings.invertVerticalLook === false, 'vertical inversion defaults off');
const stored = new Map<string, string>();
const storage = { getItem: (key: string) => stored.get(key) || null, setItem: (key: string, value: string) => { stored.set(key, value); } };
const savedProfile = new ProfileStore(storage); savedProfile.profile.settings.invertVerticalLook = true; savedProfile.save();
check(new ProfileStore(storage).profile.settings.invertVerticalLook === true, 'vertical inversion persists across reload');
check(!savedProfile.equip('svd','4x',false)&&savedProfile.profile.loadouts.svd.optic==='4x','built-in sniper optic cannot be removed or charged as an attachment');
savedProfile.profile.coins = 100; savedProfile.save(); savedProfile.reset();
check(savedProfile.profile.coins === 1000 && new ProfileStore(storage).profile.coins === 1000, 'atomic profile reset survives lifecycle save and reload');

const action = new ActionState();
const token = action.begin('reload');
check(token !== null && action.begin('heal') === null, 'exclusive actions');
check(action.complete(token!) && !action.complete(token!), 'action completion idempotency');
action.kill();
check(!action.alive && !action.ads && action.begin('throw') === null, 'dead actor blocks actions');
action.respawn();
check(action.alive && action.exclusive === 'idle', 'respawn reset');

const ids = new IdempotencySet();
check(ids.accept('death-1') && !ids.accept('death-1'), 'death scoring idempotency');

console.log(`core tests passed: ${passed}`);
